// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {monitor} from '../models';

export function AnswerQuestion(arg1:string):Promise<void>;

export function HandleQuestionAnswer(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CancelInstall():Promise<void>;

export function CompleteSetup():Promise<void>;

export function DetectSetupStatus():Promise<any>;

export function ExpandForOnboarding():Promise<void>;

export function InstallOllama():Promise<void>;

export function LoadConfig():Promise<config.Config>;

export function OnCharaClick():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetLastEvent(arg1:monitor.MonitorEvent):Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function ListOllamaModels():Promise<string[]>;

export function DeleteModel(arg1:string):Promise<void>;

export function CreateSakuraModel(arg1:string):Promise<string>;

export function RecordNewsInterest(arg1:string,arg2:boolean,arg3:string[]):Promise<void>;

export function ExpandForReview():Promise<void>;

export function CollapseFromReview():Promise<void>;

export function GetUnratedSpeeches():Promise<Array<{speech:string,personality:string,category:string,lang:string,source:string}>>;

export function RateSpeech(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<void>;
