// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerQuestion(arg1) {
  return window['go']['main']['App']['AnswerQuestion'](arg1);
}

export function HandleQuestionAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleQuestionAnswer'](arg1, arg2, arg3);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function DetectSetupStatus() {
  return window['go']['main']['App']['DetectSetupStatus']();
}

export function ExpandForOnboarding() {
  return window['go']['main']['App']['ExpandForOnboarding']();
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OnCharaClick() {
  return window['go']['main']['App']['OnCharaClick']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetLastEvent(arg1) {
  return window['go']['main']['App']['SetLastEvent'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function ListOllamaModels() {
  return window['go']['main']['App']['ListOllamaModels']();
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function CreateSakuraModel(arg1) {
  return window['go']['main']['App']['CreateSakuraModel'](arg1);
}
