// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {monitor} from '../models';

export function AnswerQuestion(arg1:string):Promise<void>;

export function CancelInstall():Promise<void>;

export function CompleteSetup():Promise<void>;

export function DetectSetupStatus():Promise<any>;

export function ExpandForOnboarding():Promise<void>;

export function InstallOllama():Promise<void>;

export function LoadConfig():Promise<config.Config>;

export function OnCharaClick():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetLastEvent(arg1:monitor.MonitorEvent):Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function ListOllamaModels():Promise<string[]>;

export function DeleteModel(arg1:string):Promise<void>;

export function CreateSakuraModel(arg1:string):Promise<string>;
