// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerQuestion(arg1) {
  return window['go']['main']['App']['AnswerQuestion'](arg1);
}

export function AppendSpeechHistory(arg1, arg2) {
  return window['go']['main']['App']['AppendSpeechHistory'](arg1, arg2);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CollapseFromReview() {
  return window['go']['main']['App']['CollapseFromReview']();
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function CreateSakuraModel(arg1) {
  return window['go']['main']['App']['CreateSakuraModel'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DetectSetupStatus() {
  return window['go']['main']['App']['DetectSetupStatus']();
}

export function ExpandForOnboarding() {
  return window['go']['main']['App']['ExpandForOnboarding']();
}

export function ExpandForReview() {
  return window['go']['main']['App']['ExpandForReview']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function GetUnratedSpeeches() {
  return window['go']['main']['App']['GetUnratedSpeeches']();
}

export function HandleQuestionAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleQuestionAnswer'](arg1, arg2, arg3);
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function ListOllamaModels() {
  return window['go']['main']['App']['ListOllamaModels']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LogGeminiActivity(arg1) {
  return window['go']['main']['App']['LogGeminiActivity'](arg1);
}

export function OnCharaClick() {
  return window['go']['main']['App']['OnCharaClick']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function RateSpeech(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RateSpeech'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RecordNewsInterest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordNewsInterest'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetClickThrough(arg1) {
  return window['go']['main']['App']['SetClickThrough'](arg1);
}

export function SetInteractiveMode(arg1) {
  return window['go']['main']['App']['SetInteractiveMode'](arg1);
}

export function SetLastEvent(arg1) {
  return window['go']['main']['App']['SetLastEvent'](arg1);
}

export function SetMonitor(arg1) {
  return window['go']['main']['App']['SetMonitor'](arg1);
}

export function TriggerTestQuestion(arg1) {
  return window['go']['main']['App']['TriggerTestQuestion'](arg1);
}

export function UpdateInteractiveRegions(arg1) {
  return window['go']['main']['App']['UpdateInteractiveRegions'](arg1);
}
