// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';
import {llm} from '../models';
import {config} from '../models';
import {monitor} from '../models';

export function AnswerQuestion(arg1:string):Promise<void>;

export function AppendSpeechHistory(arg1:string,arg2:string):Promise<void>;

export function CancelInstall():Promise<void>;

export function CollapseFromReview():Promise<void>;

export function CompleteSetup():Promise<void>;

export function CreateSakuraModel(arg1:string):Promise<string>;

export function DeleteModel(arg1:string):Promise<void>;

export function DetectSetupStatus():Promise<main.SetupStatus>;

export function ExpandForOnboarding():Promise<void>;

export function ExpandForReview():Promise<void>;

export function GetContext():Promise<context.Context>;

export function GetUnratedSpeeches():Promise<Array<llm.SpeechReviewItem>>;

export function HandleQuestionAnswer(arg1:string,arg2:number,arg3:string):Promise<void>;

export function InstallOllama():Promise<void>;

export function ListOllamaModels():Promise<Array<string>>;

export function LoadConfig():Promise<config.Config>;

export function LogGeminiActivity(arg1:string):Promise<void>;

export function OnCharaClick():Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function RateSpeech(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<void>;

export function RecordNewsInterest(arg1:string,arg2:boolean,arg3:Array<string>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetClickThrough(arg1:boolean):Promise<void>;

export function SetInteractiveMode(arg1:boolean):Promise<void>;

export function SetLastEvent(arg1:monitor.MonitorEvent):Promise<void>;

export function SetMonitor(arg1:monitor.Monitor):Promise<void>;

export function TriggerTestQuestion(arg1:string):Promise<void>;

export function UpdateInteractiveRegions(arg1:Array<number>):Promise<void>;
